---

es_index_settings:

  settings:
    analysis:
      analyzer:
        canonical_sort:
          type: custom
          tokenizer: keyword
          filter:
            - lowercase
            - pattern_replace
      filter:
        pattern_replace:
          type: pattern_replace
          pattern: >-
            ^([^a-z0-9]+|a\b|an\b|the\b)*
          replacement: ""

es_index_mapping_collection:
  collection:
    date_detection: false
    properties:
      '@context':
        type: "string"
      '@id':
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      '@type':
        type: "string"
      _rev:
        type: "object"
        enabled: false
      admin:
        properties:
          ingestDate:
            type: "date"
            format: "dateOptionalTime"
          ingestType:
            type: "object"
            enabled: false
          valid_after_enrich:
            type: "boolean"
          validation_message:
            type: "object"
            enabled: false
      description:
        type: "string"
      id:
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      ingestDate:
        type: "object"
        enabled: false
      ingestType:
        type: "object"
        enabled: false
      ingestionSequence:
        type: "long"
      title:
        type: "multi_field"
        fields:
          title:
            type: "string"
          not_analyzed:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
            include_in_all: false

es_index_mapping_item:
  item:
    date_detection: false
    properties:
      '@context':
        type: "object"
        enabled: false
      '@id':
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      '@type':
        type: "string"
      _rev:
        type: "object"
        enabled: false
      admin:
        properties:
          contributingInstitution:
            type: "string"
            include_in_all: false
          ingestDate:
            type: "date"
            format: "dateOptionalTime"
          ingestType:
            type: "object"
            enabled: false
          object_status:
            type: "long"
          sourceResource:
            properties:
              title:
                type: "string"
                analyzer: "canonical_sort"
                null_value: "zzzzzzzz"
          valid_after_enrich:
            type: "boolean"
          validation_message:
            type: "object"
            enabled: false
      aggregatedCHO:
        type: "string"
      dataProvider:
        type: "multi_field"
        fields:
          dataProvider:
            type: "string"
          not_analyzed:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
            include_in_all: false
      hasView:
        properties:
          '@id':
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          edmRights:
            type: "multi_field"
            fields:
              edmRights:
                type: "string"
              not_analyzed:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
                include_in_all: false
          format:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          rights:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
      id:
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      ingestDate:
        type: "object"
        enabled: false
      ingestType:
        type: "object"
        enabled: false
      ingestionSequence:
        type: "long"
      intermediateProvider:
        type: "multi_field"
        fields:
          intermediateProvider:
            type: "string"
          not_analyzed:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
            include_in_all: false
      isPartOf:
        properties:
          '@id':
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          name:
            type: "multi_field"
            fields:
              name:
                type: "string"
              not_analyzed:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
                include_in_all: false
      isShownAt:
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      object:
        type: "string"
        index: "not_analyzed"
        norms:
          enabled: false
        index_options: "docs"
      originalRecord:
        type: "object"
        enabled: false
      provider:
        properties:
          '@id':
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          name:
            type: "multi_field"
            fields:
              name:
                type: "string"
              not_analyzed:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
                include_in_all: false
      rights:
        type: "string"
      sourceResource:
        properties:
          '@id':
            type: "string"
          collection:
            properties:
              '@id':
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              description:
                type: "string"
              id:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              title:
                type: "multi_field"
                fields:
                  title:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
          contributor:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          creator:
            type: "string"
          date:
            properties:
              begin:
                type: "multi_field"
                fields:
                  begin:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    null_value: "-9999"
                  not_analyzed:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    include_in_all: false
              displayDate:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              end:
                type: "multi_field"
                fields:
                  end:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    null_value: "9999"
                  not_analyzed:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    include_in_all: false
          description:
            type: "string"
          extent:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          format:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          genre:
            type: "string"
          identifier:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          isPartOf:
            type: "object"
            enabled: false
          language:
            properties:
              iso639_3:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              name:
                type: "multi_field"
                fields:
                  name:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
          publisher:
            type: "multi_field"
            fields:
              publisher:
                type: "string"
              not_analyzed:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
                include_in_all: false
          relation:
            type: "string"
          rights:
            type: "string"
          spatial:
            properties:
              city:
                type: "multi_field"
                fields:
                  city:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
              coordinates:
                type: "geo_point"
              country:
                type: "multi_field"
                fields:
                  country:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
              county:
                type: "multi_field"
                fields:
                  county:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
              iso3166-2:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              name:
                type: "multi_field"
                fields:
                  name:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
              region:
                type: "multi_field"
                fields:
                  region:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
              state:
                type: "multi_field"
                fields:
                  state:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
          specType:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
          stateLocatedIn:
            properties:
              iso3166-2:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              name:
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
          subject:
            properties:
              '@id':
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              '@type':
                type: "string"
                index: "not_analyzed"
                norms:
                  enabled: false
                index_options: "docs"
              name:
                type: "multi_field"
                fields:
                  name:
                    type: "string"
                  not_analyzed:
                    type: "string"
                    index: "not_analyzed"
                    norms:
                      enabled: false
                    index_options: "docs"
                    include_in_all: false
          temporal:
            properties:
              '#text':
                type: "string"
              begin:
                type: "multi_field"
                fields:
                  begin:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    null_value: "-9999"
                  not_analyzed:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    include_in_all: false
              displayDate:
                type: "string"
              encoding:
                type: "string"
              end:
                type: "multi_field"
                fields:
                  end:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    null_value: "9999"
                  not_analyzed:
                    type: "date"
                    ignore_malformed: true
                    format: "dateOptionalTime"
                    include_in_all: false
          title:
            type: "string"
          type:
            type: "string"
            index: "not_analyzed"
            norms:
              enabled: false
            index_options: "docs"
