---

- name: Gather ec2 facts
  ec2_facts:
  when: level == 'production' or level == 'staging'
- name: De-register instance from loadbalancer
  local_action: ec2_elb
  when: level == 'production' or level == 'staging'
  become: false
  args:
    instance_id: "{{ ansible_ec2_instance_id }}"
    ec2_elbs: "{{ api_elb_name }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_region: "{{ aws_region }}"
    state: absent
- name: Wait for connections to drain
  wait_for: >-
    host="{{ inventory_hostname }}" port="{{ api_app_port }}"
    state=drained timeout=60
  ignore_errors: yes
