---

- name: Ensure that "wordpress" user exists
  user:
    name: wordpress
    comment: "Wordpress application user"
    home: /home/wordpress
    shell: /bin/bash
    groups: webapp
    state: present
  tags:
    - users
    - web

- name: Ensure that "wordpress" user's .ssh directory exists
  file: path=/home/wordpress/.ssh state=directory mode=0700 owner=wordpress group=wordpress
  tags:
    - users
    - web

- name: Prep for build with private repo (git)
  when: do_wordpress and do_deployment and not wp_theme_use_local_source
  copy: >
      src={{ github_private_key_path | default("~/.ssh/id_rsa") }}
      dest=/home/wordpress/git_private_key
      owner=wordpress group=wordpress mode=0600
  tags:
    - web

- name: Build Wordpress (local)
  when: do_wordpress and do_deployment and wp_theme_use_local_source
  become_user: wordpress
  script: build_wordpress_local.sh
  tags:
    - web

- name: Build Wordpress (remote)
  when: do_wordpress and do_deployment and not wp_theme_use_local_source
  become_user: wordpress
  script: >-
      build_wordpress_remote.sh "{{ wp_branch_or_tag }}"
  tags:
    - web

- name: Remove private key file
  when: do_wordpress and do_deployment and not wp_theme_use_local_source
  file: path=/home/wordpress/git_private_key state=absent
  tags:
    - web

- name: Ensure existence of site root
  file:
    path: /srv/www/wordpress
    state: directory
    owner: wordpress
    group: wordpress
    recurse: yes
    mode: 0755
  when: do_wordpress and do_deployment
  tags:
    - web

- name: Sync installation to site root
  script: sync_to_siteroot.sh
  become_user: wordpress
  when: do_wordpress and do_deployment
  notify:
    - reload php5-fpm
  tags:
    - web

- name: Ensure state of uploads directory
  file:
    path: /srv/www/wordpress/wp-content/uploads
    state: directory
    owner: www-data
    group: www-data
    mode: 0755
    recurse: yes
  when: do_wordpress and do_deployment
  tags:
    - web

- name: Ensure state of Wordpress configuration file
  template: >
      src=wp-config.php.j2 dest=/srv/www/wordpress/wp-config.php
      owner=wordpress group=www-data mode=0640
  when: do_wordpress and do_deployment
  notify:
    - reload php5-fpm
  tags:
    - web

- name: Update php-fpm pool for Wordpress
  template: >
      src=etc_php5_fpm_pool.d_wp.conf.j2
      dest=/etc/php5/fpm/pool.d/wp.conf
      owner=root group=root mode=0644
  notify: reload php5-fpm
  when: do_wordpress and not skip_configuration
  tags:
    - php
    - web

- name: Update webserver virtual host for Wordpress
  template: >
      src=etc_nginx_sites_available_wordpress.j2
      dest="/etc/nginx/sites-available/wordpress"
      owner=root group=root mode=0644
  notify:
    - restart nginx
  when: do_wordpress and not skip_configuration
  tags:
    - nginx
    - web

- name: Symlink webserver virtual host for Wordpress
  file: >
      src="/etc/nginx/sites-available/wordpress"
      dest="/etc/nginx/sites-enabled/wordpress"
      state=link owner=root group=root
  notify:
    - restart nginx
  when: do_wordpress and not skip_configuration
  tags:
    - nginx
    - web
