---

- name: Ensure that "omeka" user exists
  user:
    name: omeka
    comment: "Omeka application user"
    home: /home/omeka
    shell: /bin/bash
    groups: webapp
    state: present
  tags:
    - users
    - web

- name: Ensure that "omeka" user's .ssh directory exists
  file: path=/home/omeka/.ssh state=directory mode=0700 owner=omeka group=omeka
  tags:
    - users
    - web

- name: Ensure full installation of Imagemagick
  apt: pkg=imagemagick state=present
  when: not skip_configuration
  tags:
    - php
    - web

# ImageMagick policy.xml file is configured by common_php role.

- name: Update php-fpm pool for Omeka
  template: >
      src=etc_php5_fpm_pool.d_omeka.conf.j2
      dest=/etc/php5/fpm/pool.d/omeka.conf
      owner=root group=root mode=0644
  notify: restart php5-fpm
  when: not skip_configuration
  tags:
    - php
    - web

- name: Update webserver virtual host for Omeka
  template: >
      src=etc_nginx_sites_available_omeka.j2
      dest="/etc/nginx/sites-available/omeka"
      owner=root group=root mode=0644
  notify: restart nginx
  when: not skip_configuration
  tags:
    - nginx
    - web

- name: Symlink webserver virtual host for Omeka
  file: >
      src="/etc/nginx/sites-available/omeka"
      dest="/etc/nginx/sites-enabled/omeka"
      state=link owner=root group=root
  notify: restart nginx
  when: not skip_configuration
  tags:
    - nginx
    - web

- include: deploy.yml
  when: do_deployment
