---

- name: restart rsyslogd
  service: name=rsyslog state=restarted

- name: restart sysstat
  service: name=sysstat state=restarted

- name: restart munin node
  service: name=munin-node state=restarted

# The procps service is invoked like this to apply kernel perameters with
# sysctl.
- name: start procps
  service: name=procps state=started

- name: update resolv.conf
  command: resolvconf -u
