---

- include: clean.yml
  when: clean_uv | default(false)

- name: Ensure existence of the "uv" account
  user:
    name: uv
    comment: "Universal Viewer privsep user"
    home: /opt/uv
    shell: /bin/bash
    state: present
  tags:
    - users

- name: Ensure state of installation directory
  file: path=/opt/uv/universalviewer state=directory owner=uv mode=0755

- name: Ensure state of source directory
  file: path=/opt/uv/src state=directory owner=uv mode=0755

- name: Ensure state of source subdirectories
  file:
    path: "/opt/uv/src/{{ item }}"
    state: directory
    owner: uv
    mode: 0755
  with_items:
    - universalviewer-local
    - universalviewer-git

- name: Make sure that Node Version Manager is installed
  become_user: uv
  script: "../../../files/install_nvm.sh {{ uv_nvm_version }}"
  register: script_result
  changed_when: "'Success: changed' in script_result.stdout"

- include: deploy.yml
  when: do_deployment
