---

# This role is supposed to run on an Ubuntu 16 system, so make sure that Python
# 2.7 is installed. Python 3 will not work with Ansible 1.9.
- name: Update apt repos
  # "raw" because Python 2.7 may not be installed yet
  raw: apt-get update -qq
  changed_when: false
- name: Ensure that Python 2.7 is installed for Ansible
  raw: apt-get install -qq python2.7
  changed_when: false

- name: Ensure unlimited address space limit for elasticsearch user
  # https://www.elastic.co/guide/en/elasticsearch/reference/6.1/max-size-virtual-memory-check.html
  copy:
    src: etc_security_limits.d_elasticsearch.conf
    dest: /etc/security/limits.d/elasticsearch.conf
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch

- name: Ensure that Java 8 JDK is installed
  # (JDK instead of JRE for its profiling tools)
  apt:
    pkg: openjdk-8-jdk
    state: present
    update_cache: yes

- name: Check whether the correct version of Elasticsearch is installed
  shell: "dpkg-query -l elasticsearch | grep {{ elasticsearch_version }}"
  register: dpkg_query_result
  ignore_errors: yes
  changed_when: false
  always_run: yes

- name: Download elasticsearch .deb
  get_url:
    url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elasticsearch_version }}.deb"
    dest: "/var/tmp/elasticsearch-{{ elasticsearch_version}}.deb"
  when: dpkg_query_result.rc == 1
  changed_when: false

- name: Install correct version of Elasticsearch
  apt:
    deb: "/var/tmp/elasticsearch-{{ elasticsearch_version}}.deb"
  when: dpkg_query_result.rc == 1
  notify: restart elasticsearch

- name: Ensure state of systemd override directory for 'elasticsearch' service
  file:
    path: /etc/systemd/system/elasticsearch.service.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Ensure state of systemd override file for 'elasticsearch' service
  copy:
    src: override.conf
    dest: /etc/systemd/system/elasticsearch.service.d/override.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart elasticsearch

- name: Enable Elasticsearch service start on reboot
  command: systemctl enable elasticsearch
  changed_when: false

- name: Reload systemctl
  # Don't do this as a handler. Need to make sure it happens before restarting
  # or starting Elasticsearch.
  command: systemctl daemon-reload
  changed_when: false

- name: Ensure state of jvm.options Java options file
  template:
    src: jvm.options.j2
    dest: /etc/elasticsearch/jvm.options
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Ensure state of elasticsearch.yml configuration file
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Ensure state of log4j configuration file
  template:
    src: log4j2.properties.j2
    dest: /etc/elasticsearch/log4j2.properties
    owner: root
    group: elasticsearch
    mode: 0660
  notify: restart elasticsearch

- name: Ensure state of log directory
  file:
    path: "{{ elasticsearch_log_dir }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    recurse: yes
  notify: restart elasticsearch

- name: Ensure state of data directory
  file:
    path: "{{ elasticsearch_data_dir }}"
    state: directory
    owner: elasticsearch
    group: elasticsearch
    recurse: yes
  notify: restart elasticsearch
