---

- name: restart nginx
  service: name=nginx state=reloaded

- name: restart memcached
  delegate_to: "{{ item }}"
  with_items: groups.memcached
  service: name=memcached state=restarted

- name: restart unicorn
  service: name=unicorn_frontend state=restarted
