---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: API (platform) application
  hosts: api
  serial: 1
  become: yes
  roles:
    - api
  vars:
    do_deployment: true
    skip_configuration: false
  pre_tasks:
    - include: pre_post_tasks/api_pretasks.yml
  post_tasks:
    - include: pre_post_tasks/api_posttasks.yml
