---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy frontend
  hosts: frontend
  become: yes
  serial: 1
  roles:
    - frontend
  vars:
    do_deployment: true
    skip_configuration: true
  environment:
    RAILS_ENV: "{{ frontend_rails_env }}"
