---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy API
  hosts: api
  roles:
    - api
  become: yes
  serial: 1
  vars:
    do_deployment: true
    skip_configuration: true
  pre_tasks:
    - include: pre_post_tasks/api_pretasks.yml
  post_tasks:
    - include: pre_post_tasks/api_posttasks.yml
