---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy Wordpress
  hosts: wordpress
  become: yes
  serial: 1
  roles:
    - wordpress
  vars:
    do_deployment: true
    skip_configuration: true
