---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy Exhibitions
  hosts: exhibitions
  become: yes
  serial: 1
  roles:
    - omeka
  vars:
    do_deployment: true
    skip_configuration: true
