---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Deploy Ingestion Application
  hosts:
    - ingestion_app
    - worker
  become: yes
  roles:
    - ingestion_app
  vars:
    do_deployment: true
    skip_configuration: true
