---

# To run standalone, specify
# --extra-vars "level=<development|staging|production>"
# ... or see one of the convenience playbooks that includes this one with the
#     correct value.

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Elasticsearch setup
  hosts: elasticsearch
  serial: 1
  become: yes
  roles:
    - elasticsearch
  pre_tasks:
    - name: Gather ec2 facts
      ec2_facts:
      when: level == 'production' or level == 'staging'
    - name: De-register instance from loadbalancer
      local_action: ec2_elb
      when: level == 'production' or level == 'staging'
      become: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ es_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: absent
    - name: Wait for connections to drain
      when: level == 'production' or level == 'staging'
      wait_for: >-
          host="{{ inventory_hostname }}" port="9200" state=drained timeout=60
      ignore_errors: yes
  post_tasks:
    - name: Wait for ES node to come back up
      become: false
      # Assume default port, 9200.
      local_action: >
          wait_for host="{{ inventory_hostname }}" port=9200 delay=30 timeout=300
    - name: Register instance with loadbalancer again
      # Note that, on initialization of the whole environment, when there are no
      # origin servers yet behind the loadbalancer, this task could fail if the loadbalancer
      # is configured with a health check. Elasticsearch 6 by default has a safeguard
      # against "split brain syndrome" that requires a minimum number of nodes to be
      # available -- which won't be the case when you're just starting out.  You
      # can get around this by having the loadbalancer simply probe for port 9200 while you're
      # initializing everything, and then switch it later to a HTTP check for "/".
      local_action: ec2_elb
      when: level == 'production' or level == 'staging'
      become: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ es_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: present
        wait_timeout: 22
