---

- name: Gather inventory facts in case playbook is run standalone
  hosts: all

- name: Frontend (portal) site
  hosts: frontend
  serial: 1
  become: yes
  roles:
    - frontend
  vars:
    do_deployment: true
    skip_configuration: false
  environment:
    RAILS_ENV: "{{ frontend_rails_env }}"
