---

- name: Take API out of maintenance mode
  hosts: api
  become: true
  tasks:
    - name: Remove maintenance.yml file
      file: >-
        path=/srv/www/api/tmp/maintenance.yml
        state=absent
      when: not api_alternate_db_host | default(false)

- name: Take frontend out of maintenance mode
  hosts: frontend
  become: true
  tasks:
    - name: Remove maintenance.yml file
      file: >-
        path=/srv/www/frontend/tmp/maintenance.yml
        state=absent
      when: not frontend_alternate_db_host | default(false)

- name: Take Primary Source Sets out of maintenance mode
  hosts: pss
  become: true
  tasks:
    - name: Remove maintenance.yml file
      file: >-
        path=/srv/www/pss/tmp/maintenance.yml
        state=absent
      when: not pss_alternate_db_host | default(false)

- include: clear_proxy_cache.yml
