---

- name: Reboot repository database instances
  hosts:
    - dbnodes
  serial: 1
  sudo: yes
  tasks:
    - name: Gather ec2 facts
      ec2_facts:
    - name: De-register instance from loadbalancer
      local_action: ec2_elb
      sudo: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ bigcouch_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: absent
    - name: Wait for connections to drain
      wait_for: >-
          host="{{ inventory_hostname }}" port="5984" state=drained timeout=60
      ignore_errors: yes
    - name: Reboot
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for instance to come back up
      sudo: false
      local_action: >-
          wait_for host="{{ inventory_hostname }}"
          port="5984" delay=60 timeout=600
    - name: Register instance with loadbalancer again
      sudo: false
      local_action: ec2_elb
      when: level == 'production' or level == 'staging'
      sudo: false
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        ec2_elbs: "{{ bigcouch_elb_name }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        aws_region: "{{ aws_region }}"
        state: present
