---

- name: Reboot frontend
  hosts: frontend
  become: true
  serial: 1
  tasks:
    # There is nothing fancy to do yet with the frontend servers because
    # they're behind Nginx, not a loadbalancer with an API for removing
    # nodes from the pool.  Our Nginx configuration has it hit
    # the next available origin server when the first one is down.
    - name: Reboot
      command: /sbin/shutdown -r now
      async: 0
      poll: 0
      ignore_errors: true
    - name: Wait for instance to come back up
      become: false
      local_action: >-
          wait_for host="{{ inventory_hostname }}"
          port="{{ frontend_app_port }}" delay=60 timeout=600
