---

# CONSTANTS -- can not be overridden by other vars files


# You should define elasticsearch_cluster_name depending on your environment,
# either in your inventory file or in a group_vars file.
# The cluster name will default to "elasticsearch" if it's not set by this
# variable.
#
# elasticsearch_cluster_name: dpla

# This role is supposed to run on an Ubuntu 16 system, which defaults to Python
# 3, but we need Python 2.7 for Ansible. See tasks/main.yml. We have to specify
# ansible_python_interpreter.
ansible_python_interpreter: /usr/bin/python2.7

elasticsearch_version: 6.2.3
