---

- name: Clear symlink
  file: path=/opt/thumbp/src/thumbp state=absent

- name: Check out thumbp from repository
  when: not thumbp_use_local_source
  become_user: thumbp
  git:
    repo: https://github.com/dpla/thumbp.git
    dest: /opt/thumbp/src/thumbp-git
    version: "{{ thumbp_branch_or_tag }}"
    force: true

- name: Sync thumbp from mounted directory (using local source)
  when: thumbp_use_local_source
  become_user: thumbp
  script: copy_local_app.sh
  register: script_result
  changed_when: "'Success: changed' in script_result.stdout"

- name: Symlink git working copy
  file: src=/opt/thumbp/src/thumbp-git dest=/opt/thumbp/src/thumbp state=link
  when: not thumbp_use_local_source
- name: Symlink copied local directory
  file: src=/opt/thumbp/src/thumbp-local dest=/opt/thumbp/src/thumbp state=link
  when: thumbp_use_local_source

- name: Build thumbp and sync to installation directory
  become_user: thumbp
  script: build_thumbp.sh
  notify: restart thumbp
