---

api_unicorn_worker_processes: 2
api_use_local_source: false
api_branch_or_tag: master
api_rails_env: development
api_rbenv_version: 1.9.3-p547
api_alternate_db_host: false
api_index_name: dpla_alias
api_dalli_store_cache: true
api_skip_auth: no
api_repo: https://github.com/dpla/platform.git
