---

- include: playbooks/common.yml level=contentqa

- name: HTTP proxy
  hosts: contentqa_proxy_host
  become: yes
  roles:
    - contentqa_proxy

- name: Mail
  hosts: all
  become: yes
  roles:
    - aws_postfix

- include: playbooks/dbnodes.yml level=contentqa

- include: playbooks/elasticsearch.yml level=contentqa

- include: playbooks/contentqa_webapps.yml level=contentqa

- hosts: api
  become: yes
  tasks:
    - name: Ensure existence of QA API account
      # This could fail if you try to run a "contentqa" VirtualBox VM, because mail
      # will probably not be set up.
      ignore_errors: yes
      uri: >
          url=http://{{ inventory_hostname }}:{{ api_app_port }}/v2/api_key/aa22-qa-app@dp.la
          method=POST
      tags:
        - api
        - api_auth
