---

# Configuration for development VMs.

# For first-time initialization:
#   - run this with --extra-vars "initial_run=true"
#     to prevent an error with Elasticsearch shard replication.
#   - See the comment in playbooks/siteproxy.yml regarding
#     the loadbalancer health check.

- include: playbooks/common.yml level=development ingestion2=true

- name: Configure dev1 as Munin master for development
  hosts: dev1
  roles:
    - munin_master
    - monitoring_web
  vars:
    level: development
    ingestion2: true
  become: yes

- include: playbooks/dev_loadbalancer.yml ingestion2=true

- include: playbooks/elasticsearch.yml level=development ingestion2=true

- include: playbooks/postgresql.yml level=development

- include: playbooks/memcached.yml level=development

- include: playbooks/common_httpd.yml level=development

- name: Web Configuration (frontend and site)
  hosts: webapps
  become: yes
  roles:
    - common_sitenode
    - site_proxy
    - frontend
    - { role: thumbp, tags: ['thumbp']}
  vars:
    level: development
    ingestion2: true
    skip_configuration: false
    do_deployment: true

- include: playbooks/api.yml level=development ingestion2=true

- include: playbooks/redis.yml level=development

- include: playbooks/tomcat.yml level=development

- include: playbooks/solr.yml level=development

- include: playbooks/marmotta.yml level=development

- include: playbooks/ingestion_app.yml level=development
