---

# Configuration for development VMs.

# For first-time initialization:
#   - run this with --extra-vars "initial_run=true"
#     to prevent an error with Elasticsearch shard replication.
#   - See the comment in playbooks/siteproxy.yml regarding
#     the loadbalancer health check.

- include: playbooks/common.yml level=development

- name: Configure webapp1 as Munin master for development
  hosts: webapp1
  roles:
    - munin_master
    - monitoring_web
  vars:
    level: development
  become: yes

- include: playbooks/dev_loadbalancer.yml

- include: playbooks/dbnodes.yml level=development

- include: playbooks/elasticsearch.yml level=development

- include: playbooks/dev_webapps.yml level=development
