---

# Clear these out prior to copying and symlinking below

- name: Clear /home/api/api symlink
  file: path=/home/api/api state=absent

- name: Make sure that API build directories are clear
  when: clean_api | default(false)
  file:
    path: "/home/api/{{ item }}"
    state: absent
  with_items:
    - api-git
    - api-local

- name: Check out api (platform) app from its repository (git)
  git: >-
      repo="{{ api_repo }}"
      dest=/home/api/api-git
      version={{ api_branch_or_tag | default("master") }}
      force=true
  become_user: api
  when: not api_use_local_source

# Symlink to the build directory, to allow local and git builds to coexist neatly
# 1. Git deployment ...
- file: src=/home/api/api-git dest=/home/api/api state=link
  when: not api_use_local_source

- name: Check out api (platform) app from mounted directory (local)
  script: copy_local_app.sh
  when: api_use_local_source

# Symlink, as above
# 2. Local filesystem deployment ...
- file: src=/home/api/api-local dest=/home/api/api state=link
  when: api_use_local_source

- name: Update api app database configuration
  template: >
      src=database.yml.j2 dest=/home/api/api/config/database.yml
      owner=api group=webapp mode=0640
  when: not api_use_local_source

- name: Update api app settings in v1
  template: >
      src=dpla.yml.j2 dest=/home/api/api/v1/config/dpla.yml
      owner=api group=webapp mode=0640
  when: not api_use_local_source

- name: Update api unicorn.rb
  template: >
      src=unicorn.rb.j2 dest=/home/api/api/config/unicorn.rb
      owner=api group=api mode=0644

# To use "Clean rbenv", define the variable `clean_rbenv', which is not defined
# anywhere by default.
- name: Clean rbenv
  file:
    path: /home/api/.rbenv
    state: absent
  when: clean_rbenv | default(false)

- name: Make sure rbenv and bundler are current
  script: >
      ../../../files/install_ruby_tools.sh {{ api_rbenv_version }}
  become_user: api

- name: Ensure existence of live app directory
  file:
    path: /srv/www/api
    state: directory
    owner: api
    group: api
    recurse: yes
    mode: 0755

- name: Stop Unicorn (gracefully)
  # Unicorn is stopped completely, and later restarted, because we assume that
  # preload_app is true, and this option means that a SIGHUP to reload Unicorn's
  # configuration won't cause it to reload program code.  In a setting other than
  # development, the loadbalancer in front of the API node will be routing requests
  # to the other servers in the same pool.
  service: name=unicorn_api state=stopped

- name: Assert that Unicorn pid and socket files are absent
  # These could have been left behind by an earlier failure or termination
  file: >-
    path="/srv/www/api/tmp/unicorn_api.{{ item }}" state=absent
  with_items:
    - pid
    - sock

- name: Build api app
  script: >
      build_api.sh {{ api_rbenv_version }}
  become_user: api
  notify:
    - restart memcached

- name: Start Unicorn
  service: name=unicorn_api state=started
